name: build
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Update Pipfile.lock
        run: |
          pipenv lock

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

      - name: Run test suite
        run: |
          pipenv run pytest

      - name: Run black formatter
        uses: rickstaa/action-black@v1.3.3

      - name: black-action
        on: [push, pull_request]

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
            
